## Universidad Autonoma de Aguascalientes
## Departamento: Ciencias de la computacion
## Carrera: Ingenieria en Computacion Inteligente
## Curso: Machine y Deep Learning
## Maestro: Dr. Francisco Javier Luna Rosas
## Alumno: Guillermo González Lara (237864)
## Semestre: Enero_Junio del 2026

# Práctica 16: Componentes matemáticos del Deep Learning (Tensores 0D, 1D, 2D, 3D, etc.). 

En general, todos los sistemas de aprendizaje automático actuales utilizan tensores como su estructura de datos básica. Los tensores son fundamentales en el campo: tan fundamentales que Google llamó a su marco (framework) TensorFlow.

### ¿Qué es un tensor?
En esencia, un tensor es un contenedor de datos, casi siempre datos numéricos. Por lo tanto, es un contenedor de números. Quizás ya estés familiarizado con las matrices, que son tensores 2D: los tensores son una generalización de matrices a un número arbitrario de dimensiones (tenga en cuenta que, en el contexto de los tensores, una dimensión a menudo se denomina **eje**).

### Escalares (Tensores 0D)

Un tensor que contiene un solo número se llama **escalar** (o tensor escalar, o tensor de dimensión 0, o tensor 0D). En NumPy, un número `float32` o `float64` es un tensor escalar (o array escalar). 

Puedes visualizar el número de ejes de un tensor de NumPy usando el atributo `ndim`; un tensor escalar tiene 0 ejes (`ndim == 0`). El número de ejes de un tensor también se llama su rango (rank).

In [1]:
# Creación de un tensor escalar
x <- 12

print(paste("Tensor:", x))


[1] "Tensor: 12"


In [2]:
print("Dimensiones (dim):")
print(dim(x)) 

[1] "Dimensiones (dim):"
NULL


Retorna NULL porque solo es un número, entonces es 0

### Vectores (Tensores 1D)

Una matriz de números se llama **vector** o tensor 1D. Un tensor 1D se dice que tiene exactamente un eje.

In [3]:
# Creación de un vector (tensor 1D)
x <- c(12, 3, 6, 14)

print("Tensor 1D:")
print(x)


[1] "Tensor 1D:"
[1] 12  3  6 14


In [4]:
print("Dimensiones (D):")
print(length(dim(x)))


[1] "Dimensiones (D):"
[1] 0


Este vector tiene 4 entradas, por eso se llama vector de 4 dimensiones. No hay que confundir un vector 4D con un tensor 4D.
Un vector 4D tiene un solo eje, pero 4 dimensiones dentro (4 valores). Un Tensor 4D tiene 4 ejes, y una cantidad indeterminada de dimensiones (valores) a lo largo de cada eje.

### Matrices (Tensores 2D)

Una matriz (array de arrays) es una matriz o un **tensor 2D**. Una matriz tiene dos ejes (a menudo llamados filas y columnas). Puedes interpretar visualmente una matriz como una cuadrícula rectangular de números.

In [5]:
valores <- c(5, 78, 2, 34, 0, 
             6, 79, 3, 35, 1, 
             7, 80, 4, 36, 2)

# Llenamos la matriz por filas para que quede igual que en Python
x <- matrix(valores, nrow = 3, byrow = TRUE)

print("Tensor 2D (Matriz):")
print(x)

[1] "Tensor 2D (Matriz):"
     [,1] [,2] [,3] [,4] [,5]
[1,]    5   78    2   34    0
[2,]    6   79    3   35    1
[3,]    7   80    4   36    2


In [6]:
print(paste("Número de ejes (ndim):", length(dim(x))))
print("Forma del tensor (shape):")
print(dim(x))

[1] "Número de ejes (ndim): 2"
[1] "Forma del tensor (shape):"
[1] 3 5


### Tensores 3D y de mayor dimensión

Si empaquetas varias matrices (tensores 2D) en una nueva matriz, obtienes un **tensor 3D**, que puedes interpretar visualmente como un cubo de números. Al empaquetar tensores 3D en una matriz, puedes crear un tensor 4D, y así sucesivamente. En el aprendizaje profundo, generalmente manipularás tensores que van de 0D a 4D, aunque puedes llegar hasta 5D si procesas datos de video.

In [7]:
x <- array(rep(valores, 3), dim = c(3, 5, 3))

print("Tensor 3D (Cubo de números):")
print(x)

[1] "Tensor 3D (Cubo de números):"
, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    5   34   79    1    4
[2,]   78    0    3    7   36
[3,]    2    6   35   80    2

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]    5   34   79    1    4
[2,]   78    0    3    7   36
[3,]    2    6   35   80    2

, , 3

     [,1] [,2] [,3] [,4] [,5]
[1,]    5   34   79    1    4
[2,]   78    0    3    7   36
[3,]    2    6   35   80    2



In [8]:
print(paste("Número de ejes (ndim):", length(dim(x))))
print("Forma del tensor (shape):")
print(dim(x))


[1] "Número de ejes (ndim): 3"
[1] "Forma del tensor (shape):"
[1] 3 5 3


### Tensores 4D

Al empaquetar múltiples tensores 3D en una nueva estructura, obtenemos un **tensor 4D**. En el aprendizaje profundo (Deep Learning), los tensores 4D son extremadamente comunes. Por ejemplo, se utilizan constantemente para procesar lotes de imágenes, donde las cuatro dimensiones suelen representar: `(muestras/lote, altura, anchura, canales de color)`.

In [9]:

x <- array(rep(valores, 9), dim = c(3, 5, 3, 3))

print("Tensor 4D (Resumen de su estructura para no saturar la pantalla):")
str(x)

[1] "Tensor 4D (Resumen de su estructura para no saturar la pantalla):"
 num [1:3, 1:5, 1:3, 1:3] 5 78 2 34 0 6 79 3 35 1 ...


In [10]:

print(paste("Número de ejes (ndim):", length(dim(x))))
print("Forma del tensor (shape):")
print(dim(x))

[1] "Número de ejes (ndim): 4"
[1] "Forma del tensor (shape):"
[1] 3 5 3 3


### Atributos clave de un tensor

Un tensor se define por tres atributos clave:

* **Número de ejes (Rango o ndim):** Por ejemplo, un tensor 3D tiene 3 ejes y una matriz tiene 2 ejes.
* **Forma (Shape):** Es una tupla de enteros que describe cuántas dimensiones tiene el tensor a lo largo de cada eje. Por ejemplo, el tensor 2D anterior tiene forma `(3, 5)`, y el tensor 3D tiene forma `(3, 3, 5)`.
* **Tipo de datos (dtype):** Es el tipo de datos contenidos en el tensor (por ejemplo, `float32`, `uint8`, `float64`, etc.).

# Conclusiones
Un tensor es un contenedor de datos, casi siempre numérico. Las matrices son tensores en 2D

# Bibliografía

- URL: SCIKIT-LEARN
- URL: Machine learning con keras y tensor flow